server:
  port: 5002
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb://localhost:30000/clone-fb-profile-service?authSource=admin

app:
  services:
    file: http://localhost:5004
    relationship: http://localhost:5007/relationship

logging:
  level:
    root: INFO
    "[com.tam.profile]": INFO
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR